name: DirtUtils
version: '${version}'
main: gg.dirtcraft.dirtutils.Cli

commands:
  vanish:
    description: "Hides player from others. Option '-i': handles inventory actions; '-b': handles block actions."
    aliases: [v]
  dirtutils:
    description: "Main command of the DirtUtils plugin."
    aliases: [du]
